# Generated by Django 4.2.28 on 2026-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField()),
                ('Department', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
