# Generated by Django 4.2.28 on 2026-03-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Date',
            new_name='Join_Date',
        ),
    ]
