# Generated by Django 4.2.28 on 2026-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_date_studentmodel_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Join_Date',
            field=models.DateField(),
        ),
    ]
