# Generated by Django 4.2.28 on 2026-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_studentmodel_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE'), ('AI', 'AI')], max_length=100, null=True),
        ),
    ]
