# Generated by Django 4.2.28 on 2026-03-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_alter_studentmodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('EEE', 'EEE')], max_length=100, null=True),
        ),
    ]
